import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "@/common/Footer";
import NavWrapper from "@/common/NavWrapper";
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BHF Constructions",
  icons: {
    icon: "/Images/BHF_logo.jpg",
    shortcut: "/Images/BHF_logo.jpg",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <NavWrapper />
          <div className="min-h-screen">
            {children}
          </div>
        </AuthProvider>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
